organization: Campaign Finance Institute
title: Campaign Finance Law Database
description: Data inventory grid for the Campaign Finance Institute
logo: img/CFI-logo-white.svg
# production_url : http://cfinst.github.io
# (I'm assuming)

filterYear: 2016

markdown: kramdown

collections:
  modals:
    output: true

authors:
  - Curran Kelleher
  - Seemant Kulleen
