organization: Campaign Finance Institute
title: Campaign Finance Law Database
description: Data inventory grid for the Campaign Finance Institute
logo: img/CFI-logo-white.svg

# production_url : http://cfinst.github.io
# (I'm assuming)

exclude: ['package.json', 'bower.json', 'node_modules', 'bin', 'README*', 'LICENSE', 'PoCs']

markdown: kramdown

collections:
  modals:
    output: true

authors:
  - Curran Kelleher
  - Seemant Kulleen

filterYear: 2016

# The opacity of the background rect overlay with linked hover interactions.
backgroundRectFadeOpacity: 0.75
