organization: Campaign Finance Institute
title: Campaign Finance Law Databases
description: Data inventory grid for the Campaign Finance Institute
logo: img/CFI-logo-white.svg
# production_url : http://cfinst.github.io
# (I'm assuming)

markdown: kramdown
